# Site settings
name: Sedki Ben Zid
title: Sedki Ben Zid | Software Developer
description: I'm Sed, a software developer focused on building beautiful interfaces & developing distributed, microservices-based applications with RESTful APIs
url: https://sed9ydatabank.github.io/sed/
baseurl: ''
email: benzidsedki@gmail.com
cover: ''
logo: ''
resume: https://sed9ydatabank.github.io/sed/resume.pdf
social:
  - title: email
    url: mailto:benzidsedki@gmail.com
  - title: twitter
    url: ''
  - title: instagram
    url: ''
  - title: codepen
    url: ''
  - title: github
    url: https://github.com/Sed9yDataBank
  - title: linkedin
    url: https://www.linkedin.com/in/sed-bz

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
